name: obd2_flutter
description: Sample app on how-to-use basic functionality of the obd2_flutter_plugin.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  obd2_flutter_plugin:
      path: "obd2_flutter_plugin"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
